# Generated by Django 4.2.14 on 2024-08-06 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("encadenes", "0003_rename_crags_crag_rename_routes_route_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="encadenes.sector"
            ),
        ),
    ]
